### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'rc7+'

### ISSUE THREAD

**Issue by pavlinux** [spencerdodd/kernelpop#11] opened 2017-11-09 18:01 UTC
python3 kernelpop.py

##########################
#  welcome to kernelpop  #
#                        #
# let's pop some kernels #
##########################

[+] underlying os identified as a linux variant
Traceback (most recent call last):
  File "kernelpop.py", line 30, in <module>
    main()
  File "kernelpop.py", line 10, in main
    kernelpop()
  File "/tmp/kernelpop/src/kernelpop.py", line 489, in kernelpop
    kernel_v = get_kernel_version()
  File "/tmp/kernelpop/src/kernelpop.py", line 260, in get_kernel_version
    return Kernel(kernel_version["normal"])
  File "/tmp/kernelpop/src/kernelpop.py", line 15, in __init__
    self.release, self.architecture, self.uname = self.process_kernel_version(kernel_version, uname=uname)
  File "/tmp/kernelpop/src/kernelpop.py", line 185, in process_kernel_version
    k_release = int(kernel_version.split("-")[2].replace("kali", ""))
ValueError: invalid literal for int() with base 10: 'rc7+'

**Comment by pavlinux** [comment] 2017-11-09 18:01
$ uname -a
Linux amd64 4.14.0-rc7+ #18 SMP PREEMPT Sun Nov 5 05:52:33 MSK 2017 x86_64 GNU/Linux

**Comment by spencerdodd** [comment] 2017-11-09 18:22
So I'm not sure if I handled this correctly, but I fixed the parsing so that it will not crash with a ValueError. It converts 'rc7+' into '7' as in release 7. I'm not sure if this logic is correct in terms of a correct kernel version, but it won't error out. The fix is in branch https://github.com/spencerdodd/kernelpop/tree/fix-linux-version-rc-parse on commit https://github.com/spencerdodd/kernelpop/commit/eee592c61b1c122c4556f875b0aefbbd88ba84d3

**Comment by spencerdodd** [comment] 2017-11-09 18:27
Actually since it doesn't effect any other parses and all tests still pass, the fix has been merged to master

**Comment by vivami** [comment] 2017-11-10 18:01
I have a similar issue:
```
[+] underlying os identified as a linux variant
Traceback (most recent call last):
  File "../kernelpop.py", line 32, in <module>
    main()
  File "../kernelpop.py", line 8, in main
    kernelpop()
  File "/home/pwc_nl/vivami/kernelpop/src/kernelpop.py", line 503, in kernelpop
    kernel_v = get_kernel_version()
  File "/home/pwc_nl/vivami/kernelpop/src/kernelpop.py", line 266, in get_kernel_version
    return Kernel(kernel_version["normal"])
  File "/home/pwc_nl/vivami/kernelpop/src/kernelpop.py", line 15, in __init__
    self.release, self.architecture, self.uname = self.process_kernel_version(kernel_version, uname=uname)
  File "/home/pwc_nl/vivami/kernelpop/src/kernelpop.py", line 190, in process_kernel_version
    k_release = int(kernel_version.split("-")[1].split(".")[2])
IndexError: list index out of range'
```
```
$ uname -a
Linux external4 3.14-kali1-amd64 #1 SMP Debian 3.14.5-1kali1 (2014-06-07) x86_64 GNU/Linux
```
When I do a `print(kernel_version)` around line 179, it prints `Linux-3.14-kali1-amd64-x86_64-with-Kali-1.1.0-moto`, so I think its trying to process a `Linux-x.xx.xx` string there...

**Comment by spencerdodd** [comment] 2017-11-10 18:20
@vivami checking it out now. the parsing in your uname is different from what I saw previously due to `3.14-kali1-amd64` not conforming to the expected `3.14.(RELEASE)-kali1-amd64`...I'll add a special parse in. I'm going to rework the parsing to be more flexible without these edge case catches in the near future.

**Comment by spencerdodd** [comment] 2017-11-10 18:30
@vivami any chance you could give me the output of `python -c 'import platform; print(platform.platform())'`?

**Comment by spencerdodd** [comment] 2017-11-10 19:34
actually no worries. I've fixed parsing in this uname case and made the parsing and checking a little more robust to handle these issues without failure. these changes are in master now https://github.com/spencerdodd/kernelpop/commit/612d174be1ddac0c2c12e6a60334e9d802f91312

**Comment by vivami** [comment] 2017-11-10 19:39
```
$python -c 'import platform; print(platform.platform())'
Linux-3.14-kali1-amd64-x86_64-with-Kali-1.1.0-moto
```

**Comment by spencerdodd** [comment] 2017-11-10 19:44
my tests are passing with that uname and platform input now. Do you want to pull from the updated master and see if it's fixed for you as well?

**Comment by vivami** [comment] 2017-11-10 20:00
I can confirm that the parsing issue is fixed. Thanks.

**Comment by spencerdodd** [comment] 2017-11-10 20:02
Thanks a lot for the feedback! The kernel version parsing is a bit messy. That's high on my list of improvements. In the meantime, if you find any other bugs please let me know!

**Closed** 2017-11-10 20:03 UTC
